<?php

declare(strict_types=1);

use DPay\Exceptions\DPayRateLimitException;

/**
 * Paced, resumable runner for the sandbox scenarios.
 *
 * The sandbox throttles at roughly four rapid calls, so every call is spaced
 * and 429s are retried with exponential backoff. Results are appended to a
 * ledger so an interrupted run resumes instead of restarting.
 */
final class ProbeRunner
{
    private const LEDGER = __DIR__.'/.probe-ledger.json';

    public function __construct(
        private readonly float $spacingSeconds = 3.0,
        private readonly int $maxRetries = 4,
    ) {}

    /** @return array<string, mixed> */
    public function ledger(): array
    {
        if (! is_file(self::LEDGER)) {
            return [];
        }

        $raw = json_decode((string) file_get_contents(self::LEDGER), true);

        return is_array($raw) ? $raw : [];
    }

    public function record(string $scenario, string $status, string $detail): void
    {
        $ledger = $this->ledger();
        $ledger[$scenario] = ['status' => $status, 'detail' => $this->scrub($detail)];

        file_put_contents(self::LEDGER, json_encode($ledger, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
    }

    public function isDone(string $scenario): bool
    {
        return ($this->ledger()[$scenario]['status'] ?? null) === 'pass';
    }

    /**
     * Run a call, pacing it and backing off on 429.
     *
     * @template T
     * @param  callable():T  $call
     * @return T
     */
    public function paced(callable $call): mixed
    {
        for ($attempt = 0; ; $attempt++) {
            usleep((int) ($this->spacingSeconds * 1_000_000));

            try {
                return $call();
            } catch (DPayRateLimitException $e) {
                if ($attempt >= $this->maxRetries) {
                    throw $e;
                }

                $wait = (2 ** $attempt) * 5;
                fwrite(STDERR, "  429 — backing off {$wait}s\n");
                sleep($wait);
            }
        }
    }

    /**
     * Strip anything resembling an API token before it reaches disk or stdout.
     */
    public function scrub(string $text): string
    {
        return (string) preg_replace('/sb_tk_[A-Za-z0-9]+/', 'sb_tk_[REDACTED]', $text);
    }

    /**
     * Standing context for the report.
     *
     * This lives here, not in the .md file: writeReport() overwrites the
     * whole file, so any prose kept only in SANDBOX-VALIDATION.md would be
     * destroyed by the next probe run. Phrased so it stays true whatever
     * the current results are.
     */
    private const PREAMBLE = <<<'MD'
        Regenerated by [tests/sandbox/probe.php](tests/sandbox/probe.php). Superseded
        as the primary spec reference by the official DPay API spec
        (https://dpay.ly/docs/api) and its Postman collection — treat this file as
        corroborating live evidence for what the spec documents, not as the source
        of truth itself. `CLAUDE.md` explains the split in more detail.

        Two `fail` rows are known, understood gaps rather than regressions, and are
        expected until DPay changes something on their side: `edfali`'s
        Idempotency-Key replay is a DPay sandbox-side limitation (reproduced
        independently via raw `curl`, outside the SDK), and `sadad` fails because
        the gateway isn't enabled on this merchant account yet, not because of a
        code defect — see [docs/providers.md § Sadad](docs/providers.md#sadad).

        `error-*` rows are cross-cutting error-path scenarios: they pass when the
        SDK maps a real DPay failure onto the expected exception class.
        MD;

    public function writeReport(string $path): void
    {
        $lines = [
            '# Sandbox Validation Report',
            '',
            self::PREAMBLE,
            '',
            '| Scenario | Status | Detail |',
            '|---|---|---|',
        ];

        foreach ($this->ledger() as $scenario => $result) {
            $lines[] = sprintf('| `%s` | %s | %s |', $scenario, $result['status'], $result['detail']);
        }

        file_put_contents($path, implode("\n", $lines)."\n");
    }
}
